<!DOCTYPE html>
<html>
<head>
    <title>Ethics Clearance Request</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 40px; }
        h1 { text-align: center; color: #1a5276; }
        .info { margin-top: 30px; }
        .info p { margin: 10px 0; }
        .label { font-weight: bold; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <h1>Ethics Clearance Request</h1>
    <div class="info">
        <p><span class="label">Title:</span> {{ $title }}</p>
        <p><span class="label">Abstract:</span> {{ $abstract }}</p>
        <p><span class="label">Objectives:</span> {{ $objectives }}</p>
        <p><span class="label">Methodology:</span> {{ $methodology }}</p>
        <p><span class="label">Submitted by:</span> {{ $submitted_by }}</p>
        <p><span class="label">Date:</span> {{ $date }}</p>
    </div>
    <div class="footer">
        Generated by RDRIMS<br>
        This document is auto-generated and does not require a signature.
    </div>
</body>
</html>
