<?php

namespace App\Http\Controllers;

use App\Http\Requests\GenerateReportRequest;
use App\Models\Report;
use App\Services\ReportService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ReportController extends Controller
{
    public function __construct(
        private ReportService $reportService,
    ) {}

    /**
     * List reports – scoped to the requesting user's institution hierarchy.
     */
    public function index(Request $request): JsonResponse
    {
        $user = $request->user();

        $query = Report::with('generatedBy')->orderBy('generated_at', 'desc');

        // Scope reports to those generated by users within the same hierarchy.
        if ($user && !$user->hasRole('super_admin')) {
            $query->whereHas('generatedBy', function ($q) use ($user) {
                $q->hierarchical($user, 'id');
            });
        }

        $reports = $query->paginate(20);

        return response()->json($reports);
    }

    public function types(): JsonResponse
    {
        return response()->json([
            ['value' => 'projects', 'label' => 'Projects Summary'],
        ]);
    }

    public function generate(GenerateReportRequest $request): JsonResponse
    {
        $filters = $request->validated('parameters') ?? [];
        $data = $this->getReportData($request->type, $filters, $request->user());

        $report = $this->reportService->generate($request->name, $request->type, $data);

        return response()->json($report, 201);
    }

    public function download(Report $report): mixed
    {
        $this->authorize('view', $report);

        if (! Storage::disk('public')->exists($report->file_path)) {
            abort(404, 'Report file not found.');
        }

        return Storage::disk('public')->download($report->file_path, $report->name . '.pdf');
    }

    public function destroy(Report $report): JsonResponse
    {
        $this->authorize('delete', $report);

        Storage::disk('public')->delete($report->file_path);
        $report->delete();

        return response()->json(['message' => 'Report deleted.']);
    }

    /**
     * Fetch report data – always tenant-scoped via hierarchical().
     */
    private function getReportData(string $type, array $filters, $user): array
    {
        return match ($type) {
            'projects' => [
                'projects' => \App\Models\Project::with('status', 'pi')
                    ->hierarchical($user, 'pi_id')
                    ->get(),
            ],
            'outputs' => [
                'outputs' => \App\Models\Output::with('status', 'category')
                    ->when(!$user->hasRole('super_admin'), function ($q) use ($user) {
                        // Scope outputs to institution by participant users
                        $q->whereHas('participants', function ($pq) use ($user) {
                            $pq->hierarchical($user, 'id');
                        });
                    })
                    ->get(),
            ],
            'publications' => [
                'publications' => \App\Models\Publication::with('authors')
                    ->when(!$user->hasRole('super_admin'), function ($q) use ($user) {
                        $q->whereHas('project', function ($pq) use ($user) {
                            $pq->hierarchical($user, 'pi_id');
                        });
                    })
                    ->get(),
            ],
            'expenses' => [
                'expenses' => \App\Models\Expense::with('project')
                    ->when(!$user->hasRole('super_admin'), function ($q) use ($user) {
                        $q->whereHas('project', function ($pq) use ($user) {
                            $pq->hierarchical($user, 'pi_id');
                        });
                    })
                    ->get(),
            ],
            'community' => [
                'problems' => \App\Models\CommunityProblem::with('status')
                    ->when(!$user->hasRole('super_admin'), function ($q) use ($user) {
                        // Scope community problems to the user's institution
                        $q->whereHas('call', function ($cq) use ($user) {
                            $cq->visibleTo($user);
                        });
                    })
                    ->get(),
            ],
            default => [],
        };
    }
}
